function x = TCStateFun(x,u,w)
% 
%inputs x[k]
% x(1) = x21, x(2) = y21, x(3) = th21 etc.
%outputs x[k+1]
%params: u (input vector u has already been passed process noise)
%        dt (sampling time)
% u(1) = v1, u(2) = omega1, u(3) = v2, u(4) = omega2

%euler integration of continuous time dynamics x' = f(x,u)
x = x + TCStateFunContinuous(x,u,w)*0.05;
end


function dxdt = TCStateFunContinuous(x,u,w)
%evaluate the ODE 
u = u + w;
dxdt = [u(3)*cos(x(3)) ; ...
        u(3)*sin(x(3)) ; ...
        u(4) ; ...
        u(1)*cos(x(6)) ; ...
        u(1)*sin(x(6)) ; ...
        u(2)] + ...
       [x(2)*u(2)-u(1) ; ...
        -x(1)*u(2) ; ...
        -u(2) ; ...
        x(5)*u(4)-u(3); ...
        -x(4)*u(4) ;    ...
        -u(4)];
end
